# Generated by Django 4.0.4 on 2022-04-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('sqft_living', models.IntegerField()),
                ('sqft_lot', models.IntegerField()),
                ('floors', models.FloatField()),
                ('waterfront', models.IntegerField()),
                ('view', models.IntegerField()),
                ('condition', models.IntegerField()),
                ('sqft_above', models.IntegerField()),
                ('sqft_basement', models.IntegerField()),
                ('yr_built', models.IntegerField()),
                ('yr_renovated', models.IntegerField()),
                ('street', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('statezip', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'house_data',
            },
        ),
        migrations.AddIndex(
            model_name='housedata',
            index=models.Index(fields=['price'], name='price_idx'),
        ),
        migrations.AddIndex(
            model_name='housedata',
            index=models.Index(fields=['sqft_living'], name='sqft_living_idx'),
        ),
        migrations.AddIndex(
            model_name='housedata',
            index=models.Index(fields=['yr_built'], name='yr_built_idx'),
        ),
        migrations.AddIndex(
            model_name='housedata',
            index=models.Index(fields=['yr_renovated'], name='yr_renovated_idx'),
        ),
    ]
